"""Pure LLM-driven controller-core structure exporter.

This script does not use keyword rules, scenario templates, or fallback
structures. It sends the natural-language requirement directly to the model
and exports the model's JSON response as the controller-core design.

The model is instructed to design controller-body loops only, such as speed,
position, torque, voltage, current, and power loops, while keeping the output
English-formatted and assigning unique ids to every block and edge.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

DEFAULT_SETTINGS = {
    "api_key": "",
    "base_url": "https://api.siliconflow.cn/v1",
    "model": "deepseek-ai/DeepSeek-V3.2",
    "temperature": 0.0,
    "timeout": 180,
    "system_prompts": {
        "controller_core": (
            "You are an expert controller architecture designer. "
            "Design controller-body structure only from the user's natural-language requirement. "
            "Do not use scenario templates, heuristics, or default loop sets. "
            "Return strict JSON only, with English text only in the design fields. "
            "Every block, edge, and path must have a unique stable id."
        ),
    },
}


def default_settings_path() -> Path:
    return Path(__file__).with_name("llm_settings.json")


def read_llm_settings(path: str | Path | None = None) -> dict[str, Any]:
    config_path = Path(path or default_settings_path())
    if not config_path.exists():
        return dict(DEFAULT_SETTINGS)

    with open(config_path, "r", encoding="utf-8-sig") as handle:
        loaded = json.load(handle)

    merged = dict(DEFAULT_SETTINGS)
    merged.update({key: value for key, value in loaded.items() if key != "system_prompts"})

    prompts = dict(DEFAULT_SETTINGS.get("system_prompts") or {})
    prompts.update(loaded.get("system_prompts") or {})
    merged["system_prompts"] = prompts
    return merged


def resolve_api_key(settings: dict[str, Any]) -> str:
    return (
        str(settings.get("api_key") or "").strip()
        or os.getenv("SILICONFLOW_API_KEY", "").strip()
        or os.getenv("OPENAI_API_KEY", "").strip()
    )


def strip_code_fence(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```[a-zA-Z0-9_\-]*\n", "", cleaned)
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
    return cleaned.strip()


def call_chat(api_key: str, base_url: str, model: str, system_prompt: str, user_prompt: str, temperature: float, timeout: int) -> dict[str, Any]:
    url = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model,
        "temperature": temperature,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    }
    data = json.dumps(payload).encode("utf-8")

    request = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read().decode("utf-8")
            return json.loads(body)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTPError {error.code}: {detail}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"URLError: {error}") from error


def extract_text(response_json: dict[str, Any]) -> str:
    choices = response_json.get("choices") or []
    if not choices:
        return ""
    message = choices[0].get("message") or {}
    return message.get("content") or ""


def build_user_prompt(requirement: str) -> str:
    return (
        "Task: Design a controller-core structure from a Chinese natural-language requirement.\n"
        "Hard constraints:\n"
        "1) Return STRICT JSON object only, no markdown, no prose.\n"
        "2) The design must be generated by the model; do not use any preset scenario template or fallback structure.\n"
        "3) Output must be English-formatted in all design fields.\n"
        "4) Only controller-body loops are allowed: examples include position, speed, torque, voltage, current, and power loops.\n"
        "5) Do not include protection, modulation, state machine, or power-stage blocks unless the requirement explicitly asks for them.\n"
        "6) Every block, edge, and path must have a unique stable id.\n"
        "7) Infer the minimum necessary loop hierarchy from the requirement and make the hierarchy explicit.\n"
        "8) Prefer controller architectures such as position -> speed -> torque -> current -> voltage when the requirement implies a cascaded control chain.\n"
        "9) Do not invent non-control infrastructure.\n"
        "10) The JSON root must contain at least: id, name, version, language, requirement, summary, control_scope, blocks, edges, layout, design_rules, output_format.\n\n"
        f"Natural-language requirement:\n{requirement.strip()}\n\n"
        "Expected output example shape:\n"
        "{\"id\":\"...\",\"name\":\"...\",\"version\":1,\"language\":\"en\",\"requirement\":\"...\",\"summary\":\"...\",\"control_scope\":\"controller_body_only\",\"blocks\":[],\"edges\":[],\"layout\":{},\"design_rules\":[],\"output_format\":{}}\n"
    )


def parse_response_json(text: str) -> dict[str, Any]:
    cleaned = strip_code_fence(text)
    data = json.loads(cleaned)
    if not isinstance(data, dict):
        raise ValueError("model response is not a JSON object")
    return data


def validate_structure(structure: dict[str, Any]) -> None:
    required_keys = ["id", "name", "version", "language", "requirement", "summary", "control_scope", "blocks", "edges", "layout", "design_rules", "output_format"]
    missing = [key for key in required_keys if key not in structure]
    if missing:
        raise ValueError(f"missing required keys: {', '.join(missing)}")
    if not isinstance(structure.get("blocks"), list):
        raise ValueError("blocks must be a list")
    if not isinstance(structure.get("edges"), list):
        raise ValueError("edges must be a list")
    if not isinstance(structure.get("layout"), dict):
        raise ValueError("layout must be an object")
    if not isinstance(structure.get("design_rules"), list):
        raise ValueError("design_rules must be a list")
    if not isinstance(structure.get("output_format"), dict):
        raise ValueError("output_format must be an object")


def build_controller_core_structure(requirement: str, settings: dict[str, Any]) -> dict[str, Any]:
    api_key = resolve_api_key(settings)
    if not api_key:
        raise RuntimeError("missing API key in llm settings or environment")

    system_prompt = settings.get("system_prompts", {}).get("controller_core") or DEFAULT_SETTINGS["system_prompts"]["controller_core"]
    temperature = float(settings.get("temperature", 0.0))
    timeout = int(settings.get("timeout", 180))
    model = str(settings.get("model") or DEFAULT_SETTINGS["model"])
    base_url = str(settings.get("base_url") or DEFAULT_SETTINGS["base_url"])

    response_json = call_chat(
        api_key=api_key,
        base_url=base_url,
        model=model,
        system_prompt=system_prompt,
        user_prompt=build_user_prompt(requirement),
        temperature=temperature,
        timeout=timeout,
    )
    text = extract_text(response_json)
    if not text.strip():
        raise RuntimeError("empty model response")

    structure = parse_response_json(text)
    validate_structure(structure)
    return structure


def export_json(output_path: Path, requirement: str, settings_path: str | Path | None = None) -> Path:
    settings = read_llm_settings(settings_path)
    payload = build_controller_core_structure(requirement, settings)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export a controller-core JSON design using a large language model.")
    parser.add_argument(
        "requirement",
        nargs="?",
        default="我需要设计一款速度控制系统",
        help="Natural-language requirement for the controller-core design.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("controller_core_structure.json"),
        help="Path to the JSON file to generate.",
    )
    parser.add_argument(
        "--llm-config",
        type=Path,
        default=default_settings_path(),
        help="Path to the LLM settings JSON file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    exported = export_json(args.output, args.requirement, settings_path=args.llm_config)
    print(f"Exported controller core structure to {exported}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
