from __future__ import annotations

import json
from pathlib import Path

from .knowledge_base import ModuleCatalog
from .models import ControlStructure, LayerSelection, ProgramArtifact, UserRequirement


def build_structure(req: UserRequirement, catalog: ModuleCatalog) -> ControlStructure:
    # Five-layer structure required by report: trajectory, mech, distributor, current, observer.
    layers = [
        LayerSelection("trajectory", catalog.trajectory[0], {"jerk_limit": 0.1}),
        LayerSelection("mech", catalog.mech[0], {"kp": 1.5, "ki": 0.8}),
        LayerSelection("distributor", catalog.distributor[0], {"id_ref": 0.0}),
        LayerSelection("current", catalog.current[0], {"kp": 2.0, "ki": 100.0}),
        LayerSelection("observer", catalog.observer[0], {"lpf_bw": 30.0}),
    ]

    if req.control_mode == "position":
        layers[1] = LayerSelection("mech", "ctl_step_vel_pos_ctrl", {"kp": 2.0, "ki": 1.0})
    if req.scenario == "ev":
        layers[4] = LayerSelection("observer", "ctl_step_pmsm_esmo", {"lpf_bw": 45.0})

    return ControlStructure(layers=layers)


def render_ctl_main(structure: ControlStructure) -> str:
    body = []
    for layer in structure.layers:
        body.append(f"    // {layer.name} layer")
        body.append(f"    {layer.module}(&ctrl_ctx.{layer.name});")

    joined = "\n".join(body)
    return f"""// Auto-generated by GMP Generator Engine.
#include <gmp_core.h>
#include <ctrl_settings.h>

#include \"ctl_main.h\"

#include <xplt.peripheral.h>

volatile fast_gt flag_system_enable = 0;
volatile fast_gt flag_system_running = 0;
volatile fast_gt flag_error = 0;

gmp_ctrl_ctx_t ctrl_ctx;

void ctl_init(void)
{{
    ctl_disable_output();

    // TODO: initialize controller modules according to ctrl_settings.h.
    // Example:
    // ctl_init_pmsm_controller(&ctrl_ctx.current, CONTROLLER_FREQUENCY);
}}

void ctl_mainloop(void)
{{
    // Main-loop tasks: state machine dispatch, diagnostics, and non-ISR control decisions.
    return;
}}

void ctl_dispatch(void)
{{
{joined}

    // Keep this call in ISR periodic loop to align with GMP controller stepping model.
    gmp_base_ctl_step();
}}
"""


def render_ctl_main_h(structure: ControlStructure) -> str:
    layer_fields = "\n".join(
        [f"    void* {layer.name};  // bind to {layer.module}" for layer in structure.layers]
    )
    return f"""// Auto-generated by GMP Generator Engine.
#ifndef _FILE_CTL_MAIN_H_
#define _FILE_CTL_MAIN_H_

#ifdef __cplusplus
extern \"C\" {{
#endif

#include <xplt.peripheral.h>

#include <ctl/ctl_core.h>

typedef struct _tag_gmp_ctrl_ctx
{{
{layer_fields}
}} gmp_ctrl_ctx_t;

extern volatile fast_gt flag_system_enable;
extern volatile fast_gt flag_system_running;
extern volatile fast_gt flag_error;

extern gmp_ctrl_ctx_t ctrl_ctx;

void ctl_init(void);
void ctl_mainloop(void);
void ctl_dispatch(void);

#ifdef __cplusplus
}}
#endif

#endif // _FILE_CTL_MAIN_H_
"""


def render_user_main_c() -> str:
    return """// Auto-generated by GMP Generator Engine.
#include <gmp_core.h>

#include \"user_main.h\"

GMP_NO_OPT_PREFIX
void init(void) GMP_NO_OPT_SUFFIX
{
    // TODO: initialize at_device, scheduler and optional command handlers.
}

GMP_NO_OPT_PREFIX
void mainloop(void) GMP_NO_OPT_SUFFIX
{
    // TODO: run scheduler dispatch for non-blocking background tasks.
    // Example: gmp_scheduler_dispatch(&sched);
}
"""


def render_user_main_h() -> str:
    return """// Auto-generated by GMP Generator Engine.
#ifndef _FILE_USER_MAIN_H_
#define _FILE_USER_MAIN_H_

#ifdef __cplusplus
extern \"C\" {
#endif

void init(void);
void mainloop(void);
void setup_peripheral(void);

void ctl_init(void);
void ctl_mainloop(void);

#ifdef __cplusplus
}
#endif

#endif // _FILE_USER_MAIN_H_
"""


def generate_program(req: UserRequirement, catalog: ModuleCatalog) -> ProgramArtifact:
    structure = build_structure(req, catalog)
    files = {
        "implement/common/ctl_main.c": render_ctl_main(structure),
        "implement/common/ctl_main.h": render_ctl_main_h(structure),
        "implement/common/user_main.c": render_user_main_c(),
        "implement/common/user_main.h": render_user_main_h(),
    }
    metadata = {
        "requirement": req.text,
        "scenario": req.scenario,
        "control_mode": req.control_mode,
        "layers": [
            {
                "name": x.name,
                "module": x.module,
                "params": x.params,
            }
            for x in structure.layers
        ],
    }
    return ProgramArtifact(
        source_code=files["implement/common/ctl_main.c"],
        metadata=metadata,
        files=files,
    )


def write_artifacts(artifact: ProgramArtifact, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for rel_path, content in artifact.files.items():
        file_path = out_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")

    # Backward-compatible top-level copy for quick preview.
    (out_dir / "ctl_main.c").write_text(artifact.source_code, encoding="utf-8")

    (out_dir / "structure.json").write_text(
        json.dumps(artifact.metadata, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
